GravitLauncher/Launcher

- Launcher/src/main/java/ru/gravit/launcher/LauncherEngine.java
- Launcher/src/main/java/ru/gravit/launcher/client/ClientLauncher.java
- LauncherAPI/src/main/java/ru/gravit/launcher/request/auth/AuthRequest.java
- libLauncher/src/main/java/ru/gravit/launcher/Launcher.java
Надо бы еще сделать, что бы градл не паковал их если аван отключен
> Allow to disable Avanguard

- Launcher/runtime/init.js
Why this button if there is not a scalable design?
> Disable resizable button

- docs/EN-changes.md
> English translation improvements

- Launcher/runtime/dialog/overlay/options/options.js
Поддержка многослойного дерева вложенности / новая механика выбора одного из опциональных модов.
Сортировка дерева производится так же, как и в прошлой версии (Сначала всё как config.js, потом всё остальное). Необходимо соблюдать порядок, это важно. Т.к. дерево на нём завязано. То есть модификации должны быть по порядку {Кор-мод}{Мод}{Аддон}, с соответствующими им уровнями вложенности.
Теперь выбор "одного из" работает со всеми модами/субмодами. (К примеру: При включении миникарты - отключится неи со всеми его аддонами. Т.к. NEI и миникарта имели общий флаг группы [onlyOneGroup]  и соответственно включенный параметр [onlyOne])
Видео с демонстрацией работы вложенности/зависимости и функции выбора "одного из": https://lww.page.link/FKec
> Update optional mods.. Again... [options.js]

- Launcher/runtime/dialog/overlay/settings/settings.fxml
Добавлен диалог подтверждения/отказа переноса файлов при смене директории.
> Add transfer dialog (settings.fxml)

- Launcher/runtime/dialog/overlay/settings/settings.js
Я программист-экономист... Чем я вообще занимаюсь...
> Add Transfer dialog (settings.js)

- Launcher/runtime/dialog/overlay/options/options.js
Если модификация была в профайле, но не была в конфиге - дерево модификаций пыталось переключить несуществующую. Что приводило к неправильной работе веток.
> Optional mods fix.

- Launcher/runtime/dialog/dialog.js
А если профайл удалили, а у пользователя до сих пор выбран этот сервер?!
Верно! Крушиться с истериками!
Либо подыматься до последнего существующего клиента, что и подразумевает данная правка.
> IOOBE Fix #2

- LaunchServer/src/main/java/ru/gravit/launchserver/manangers/NodeTransformer.java
Squash + branch del. Облегчил жизнь юзерам dle.
> Upd modules + node transformer fix.

- LaunchServer/src/main/java/ru/gravit/launchserver/socket/ServerSocketHandler.java
> Modules upd + Integer -> int.

- LaunchServer/src/main/java/ru/gravit/launchserver/LaunchServer.java
- LaunchServer/src/main/java/ru/gravit/launchserver/command/hash/IndexAssetCommand.java
> Config fix

- Launcher/src/main/java/ru/gravit/launcher/ClientLauncherWrapper.java
`Restart Launcher *witch* JavaAgent...`?
> Фикс опечатки

- README.md
> [DOCS] Правки README.

- LaunchServer/src/main/java/ru/gravit/launchserver/LaunchServer.java
- LaunchServer/src/main/java/ru/gravit/launchserver/Updater.java
- LaunchServer/src/main/resources/ru/gravit/launchserver/defaults/config.cfg
- libLauncher/src/main/java/ru/gravit/launcher/profiles/ClientProfile.java
- libLauncher/src/main/java/ru/gravit/utils/Version.java
> Сравнение с версией на гитхабе в Updater.

- Launcher/src/main/java/ru/gravit/launcher/client/ClientLauncher.java
- Launcher/src/main/java/ru/gravit/launcher/client/LauncherSettings.java
- libLauncher/src/main/java/ru/gravit/launcher/hasher/FileNameMatcher.java
> [ANY] Выполнено organize imports.

- Launcher/runtime/dialog/dialog.js
- Launcher/runtime/dialog/overlay/processing/processing.js
Доработал выбор типа авторизации через ComboBox, но не сделал сохранение выбранного поля
> Доработал ComboBox с выбором типа авторизации

- Launcher/runtime/dialog/scenes/options/options.js
Жертвуя Tab-овским выбором чекбоксов. 
Если кто придумает более элегантное решение - переделайте ;D
> [FIX] Правка откидываний в опц. модах

- LaunchServer/src/main/java/pro/gravit/launchserver/auth/provider/RequestAuthProvider.java
Рекомендую посадить на кол автора этого шедевра!
> fix RequestAuthProvider

- Launcher/runtime/config.js
- Launcher/runtime/dialog/dialog.js
- Launcher/runtime/init.js
Добавил настройку на включение своей jvm в runtime
> Добавление своей jvm в runtime

- Launcher/runtime/config.js
- Launcher/runtime/dialog/dialog.js
- Launcher/runtime/dialog/overlay/debug/debug.css
- Launcher/runtime/dialog/overlay/debug/debug.js
- Launcher/runtime/dialog/overlay/processing/processing.css
- Launcher/runtime/dialog/overlay/processing/processing.js
- Launcher/runtime/dialog/overlay/settings/settings.css
- Launcher/runtime/dialog/overlay/settings/settings.js
- Launcher/runtime/dialog/overlay/update/update.css
- Launcher/runtime/dialog/overlay/update/update.js
- Launcher/runtime/dialog/scenes/options/options.js
- Launcher/runtime/dialog/servers.css
- Launcher/runtime/dialog/styles.css
- Launcher/runtime/init.js
> [ANY] Js/css pretty print

- Launcher/runtime/config.js
- Launcher/runtime/dialog/dialog.js
- Launcher/runtime/dialog/scenes/login/login.fxml
- Launcher/runtime/dialog/scenes/mainmenu/mainmenu.fxml
- Launcher/runtime/dialog/styles.css
> [FEATURE] Простое добавление ссылок без модификации js

- Launcher/runtime/dialog/overlay/update/update.css
- Launcher/src/main/java/pro/gravit/launcher/client/ClientLauncher.java
> [ANY] Фикс флага

- README.md
> Обновлена ссылка на Discord

- LauncherAPI/src/main/java/pro/gravit/launcher/profiles/ClientProfile.java
> Add 1.16.4 suport

- LauncherAPI/src/main/java/pro/gravit/launcher/request/uuid/BatchProfileByUsernameRequest.java
Массив забыли проинициализировать. Вылетает NPE при обращении к полям client/username.
> [FIX] NPE в BatchProfileByUsernameRequest

- .github/workflows/push.yml
Сделал парсинг версии из файла для релиза
> [FIX] GitHub Actions

- LauncherAPI/src/main/java/pro/gravit/launcher/profiles/ClientProfile.java
> Support 1.18.2

- LaunchServer/src/main/java/pro/gravit/launchserver/auth/core/HttpAuthCoreProvider.java
Пока не тестил, потещу мб чето поменяется
> Add to HttpAuthCoreProvider the AuthSupportHardware implementation 
